### ISSUE TITLE
Shouldn't `disko.json` be called `disko.nix`?

### ISSUE THREAD

**Issue by bittner** [llakala/nixos#82]
From looking at the file [disko.json](https://github.com/llakala/nixos/blob/main/hosts/framework/config/disko.json) the syntax appears to be Nix language.

Shouldn't the file hence better be renamed to `disko.nix`? Or is there a reason why you use the `.json` file extension?

**Comment by llakala** [comment]
That's just a cursed thing where I previously had Disko set up, but had to reinstall so I disabled it. However, I have a function that auto-imports all Nix files, so I renamed it to a JSON file so it wouldn't get imported.
